console.log(false && true)
console.log(false && false)
console.log(true && true)
console.log(false && true)
console.log(false || true)
console.log(false || false)
console.log(true || true)
console.log(false || true)